#import "../fragments/MediaMetadata.gql"

query Dramas {
	dramas: getDramas {
		id
		title
		year
		director
		actors
		schedule
		img {
			...MediaMetadata
		}
		scenes {
			...MediaMetadata
		}
	}
}
