import React, { useEffect, useState } from "react";

import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import * as Icons from "@fortawesome/free-brands-svg-icons";

import { execAsync } from "../assets/ts/async";

type HomeData = {
    title: string
};

type FooterData = {
    sns: {
        name: string,
        url: string
    }[]
};

const AppLayout: NextPage = ({ children }) => {
    let [title, setTitle] = useState("Hello");
    let [iconsHtml, setIconsHtml] = useState([<React.Fragment key={0} />]);

    useEffect(() => {
        fetch("/api/home")
            .then(data => data.json())
            .then((data: HomeData) => setTitle(data.title));
        fetch("/api/footer")
            .then(data => data.json())
            .then((data: FooterData) => {
                setIconsHtml(data.sns.map((obj, i) => {
                    switch (obj.name) {
                    case "instagram": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faInstagram} /></a>;
                    case "facebook": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faFacebook} /></a>;
                    case "twitter": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faTwitter} /></a>;
                    case "line": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faLine} /></a>;
                    case "youtube": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faYoutube} /></a>;
                    case "pinterest": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faPinterest} /></a>;
                    case "tiktok": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faTiktok} /></a>;
                    case "snapchat": return <a key={i + "-" + obj.name} href={obj.url} target="_blank"><FontAwesomeIcon size="1x" icon={Icons.faSnapchat} /></a>;
                    default: return <a key={i} href="#" />;
                    }
                }));
            });
    }, []);

    return (
        <div className="text-no-drag">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="app-header">
                <div>
                    <Link href="/">
                        <h1>{title}</h1>
                    </Link>
                </div>
                <nav>
                    <ul>
                        <li><Link scroll={false} href="/about"><h4>ABOUT</h4></Link></li>
                        <li><Link scroll={false} href="/movies"><h4>MOVIES</h4></Link></li>
                        <li><Link scroll={false} href="/drama"><h4>DRAMA</h4></Link></li>
                        <li><Link scroll={false} href="/theater"><h4>THEATER</h4></Link></li>
                        <li><Link scroll={false} href="/contact"><h4>CONTACT</h4></Link></li>
                    </ul>
                </nav>
            </header>
            {children}
            <footer className="app-footer">
                <div>©Copyright 2021. All Rights Reserved.</div>
                {iconsHtml}
            </footer>
        </div>
    );
};

export default AppLayout;
