type Common {
	title: String!
	headerTitle: String!
}

type MediaMetadata {
	filename: String
	width: Float
	height: Float
}

type AboutMetadata {
	label: String!
	value: String!
}

type UpdatedAboutMetadata {
	name: String!
	metadata: [AboutMetadata!]
}

type AboutComment {
	id: String!
	comment: String!
	date: String!
}

type About {
	name: String!
	birth: String!
	info: String!
	metadata: [AboutMetadata!]
	img: MediaMetadata
	comments: [AboutComment!]
}

type Movies {
	id: String!
	title: String!
	year: Int!
	director: String!
	actors: [String!]
	awards: [String!]
	img: MediaMetadata
	video: MediaMetadata
	scenes: [MediaMetadata!]
}

type Dramas {
	id: String!
	title: String!
	year: Int!
	director: String
	actors: [String!]
	schedule: String
	img: MediaMetadata
	scenes: [MediaMetadata!]
}

type Theaters {
	id: String!
	title: String!
	theater: String
	year: Int!
	schedule: String
	img: MediaMetadata
	scenes: [MediaMetadata!]
}

type Contact {
	email: String!
	img: MediaMetadata
}

type Sns {
	name: String!
	url: String!
}

type Footer {
	sns: [Sns!]
}

type Secret {
	password: String!
}

type Query {
	getCommon: Common!
	getHome: [MediaMetadata!]
	getAbout: About!
	getMovies: [Movies!]
	getDramas: [Dramas!]
	getTheaters: [Theaters!]
	getContact: Contact!
	getFooter: Footer!
}

type Mutation {
	auth(password: String!): Boolean!
	AboutMetadata_update(input: UpdateAboutMetadataInput!): UpdatedAboutMetadata!
	AboutImg_update(input: MediaMetadataInput!): MediaMetadata!
	AboutComment_create(input: AboutCommentInput!): AboutComment!
	AboutComment_remove(id: String!): String!
	Movies_create(createMoviesInput: CreateMoviesInput!): Movies!
	Movies_update(updateMoviesInput: UpdateMoviesInput!): Movies!
	Movies_remove(id: String!): String!
	Movies_removeByYear(year: Int!): Int!
	Dramas_create(createDramasInput: CreateDramasInput!): Dramas!
	Dramas_update(updateDramasInput: UpdateDramasInput!): Dramas!
	Dramas_remove(id: String!): String!
	Dramas_removeByYear(year: Int!): Int!
	Theaters_create(createTheatersInput: CreateTheatersInput!): Theaters!
	Theaters_update(updateTheatersInput: UpdateTheatersInput!): Theaters!
	Theaters_remove(id: String!): String!
	Theaters_removeByYear(year: Int!): Int!
	ContactEmail_update(email: String!): String!
}

input MediaMetadataInput {
	filename: String
	width: Float
	height: Float
}

input AboutMetadataInput {
	label: String!
	value: String!
}

input AboutCommentInput {
	comment: String!
	date: String!
}

input UpdateAboutMetadataInput {
	name: String!
	metadata: [AboutMetadataInput!]
}

input AboutCommentInput {
	comment: String!
	date: String!
}

input CreateMoviesInput {
	year: Int!
	title: String!
	director: String!
	actors: [String!]
	awards: [String!]
	img: MediaMetadataInput
	video: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}

input UpdateMoviesInput {
	id: String!
	year: Int!
	title: String!
	director: String!
	actors: [String!]
	awards: [String!]
	img: MediaMetadataInput
	video: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}

input CreateDramasInput {
	title: String!
	year: Int!
	director: String
	actors: [String!]
	schedule: String
	img: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}

input UpdateDramasInput {
	id: String!
	title: String!
	year: Int!
	director: String
	actors: [String!]
	schedule: String
	img: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}

input CreateTheatersInput {
	title: String!
	theater: String
	year: Int!
	schedule: String
	img: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}

input UpdateTheatersInput {
	id: String!
	title: String!
	theater: String
	year: Int!
	schedule: String
	img: MediaMetadataInput
	scenes: [MediaMetadataInput!]
}
